name: dinov2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - rapidsai
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - cuda-version=11.7
  - torchvision=0.15.0
  - mkl=2024.0.0
  - numpy<2
  - setuptools<81
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - cuml=24.02
  - pip:
      - xformers==0.0.18
      - submitit
